// Function to generate signup payload with overrides
const generateSignupPayload = (overrides = {}) => ({
    userEmail: "newuser@gmail.com",
    userPassword: "randomPassword",
    userName: "User",
    rollNumber: "cb.en.u4cse22447",
    phoneNumber: "8654789123",
    collegeName: "Amrita",
    collegeCity: "Chennai",
    userDepartment: "CSE",
    academicYear: 2022,
    degree: "B.Tech",
    isAmrita: true,
    ...overrides,
});

export const signupTestCases = [
    {
        name: "Invalid email - should return error",
        payload: generateSignupPayload({ userEmail: "invalidemail" }),
        expectedStatus: 400,
        expectedMessage: "Invalid or missing email.",
        expectedData: {},
    },
    {
        name: "Invalid password - should return error",
        payload: generateSignupPayload({ userPassword: "pass" }),
        expectedStatus: 400,
        expectedMessage: "Invalid or missing password.",
        expectedData: {},
    },
    {
        name: "Invalid user name - should return error",
        payload: generateSignupPayload({ userName: 214 }),
        expectedStatus: 400,
        expectedMessage: "Invalid or missing userName.",
        expectedData: {},
    },
    {
        name: "Invalid roll number - should return error",
        payload: generateSignupPayload({ rollNumber: "" }),
        expectedStatus: 400,
        expectedMessage: "Invalid or missing rollNumber.",
        expectedData: {},
    },
    {
        name: "Invalid phone number - should return error",
        payload: generateSignupPayload({ phoneNumber: "12345" }),
        expectedStatus: 400,
        expectedMessage: "Invalid or missing phoneNumber.",
        expectedData: {},
    },
    {
        name: "Invalid college name - should return error",
        payload: generateSignupPayload({ collegeName: "  " }),
        expectedStatus: 400,
        expectedMessage: "Invalid or missing collegeName.",
        expectedData: {},
    },
    {
        name: "Invalid college city - should return error",
        payload: generateSignupPayload({ collegeCity: 123 }),
        expectedStatus: 400,
        expectedMessage: "Invalid or missing collegeCity.",
        expectedData: {},
    },
    {
        name: "Invalid department - should return error",
        payload: generateSignupPayload({ userDepartment: undefined }),
        expectedStatus: 400,
        expectedMessage: "Invalid or missing userDepartment.",
        expectedData: {},
    },
    {
        name: "Invalid academic year - should return error",
        payload: generateSignupPayload({ academicYear: "2022" }),
        expectedStatus: 400,
        expectedMessage: "Invalid or missing academicYear.",
        expectedData: {},
    },
    {
        name: "Invalid degree - should return error",
        payload: generateSignupPayload({ degree: null }),
        expectedStatus: 400,
        expectedMessage: "Invalid or missing degree.",
        expectedData: {},
    },
    {
        name: "Invalid isAmrita - should return error",
        payload: generateSignupPayload({ isAmrita: 1 }),
        expectedStatus: 400,
        expectedMessage: "Invalid isAmrita Value",
        expectedData: {},
    },
];
